### ISSUE TITLE
As a player, I want to be able to attack the opponents’ pieces in order to get closer to victory.

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#11]
- [x] A piece can only attack an opponents’ piece if it stands next to it. 
- [x] The piece with the higher rank survives, the losing piece will be removed. 
- [x] Mines will win every battle except for battles against the miner. 
- [x] Pieces with rank 1 win against rank 10 
- [x] If two fighting pieces have the same rank, both will be removed. 
- [x] sopra-fs23-group-22/sopra-fs23-group-22-server#37
- [x] #85
- [x] #86
- [x] sopra-fs23-group-22/sopra-fs23-group-22-client#26
- [x] #89
- [x] #133
- [x] #134

**Comment by ShiranLiu** [comment]
tentative version: a very detailed skeleton code of the design, which might have errors and to be finalised and test together with front-end development. Since we cannot implement every perfectly at the moment due to lake of other implementation detail, such as data converted to back-end, front-end implementation etc.
