### ISSUE TITLE
peripheral functions that invoke the corresponding move strategy of a certain piece type (tentative version)

### ISSUE THREAD

**Issue by stefanpluess** [sopra-fs23-group-22/sopra-fs23-group-22-server#41]

**Comment by ShiranLiu** [comment]
When a piece is to be moved from the source square to a target square, if the target square contains a piece, it is an attack operation, otherwise it is a move operation. The peripheral functions and classes should tell whether it is a attack/move operation and delegate it to the corresponding operate/move strategies.

**Comment by stefanpluess** [comment]
[aa3646d](https://github.com/sopra-fs23-group-22/sopra-fs23-group-22-server/commit/aa3646d888a342eb9fa64c1d56ad1f590419b267)
